### ISSUE TITLE
Dungeon Raid can gen uncompletable

### ISSUE THREAD

**Issue by thephoenixlodge** [Lemonszz/ArcaneWorld#3]
**Mod Version**:  0.0.8
**Forge Version**: 2772

**What happens**:
Currently, if the Lava parkour room generates as the first room from the entrance, it's impossible to get out of the original room, as the stairs for the lava room block the door.
https://i.imgur.com/uGUSOZf.png

**Comment by Lemonszz** [comment]
oops. 

If you happen to still be stuck (or anyone else finds this issue), the best way to get out would likely be to put yourself into spectator mode to fly though.

I'll get this fixed up for the next release.

**Comment by thephoenixlodge** [comment]
Yea that was the solution we went with at the time

**Comment by Lemonszz** [comment]
Finally got this fixed for the next release
