### ISSUE TITLE
Pack maker request: ritual command

### ISSUE THREAD

**Issue by wizard1399** [Lemonszz/ArcaneWorld#4]
Could you add support for rituals that execute command block strings? An example of usage might be running a test for command to check a condition and if returns true, teleport player to a dimension.  For example, I want to create a ritual that will check a players inventory for certain blacklist items. If those items are not found, the ritual will teleport the player to a dimesion.

**Comment by Lemonszz** [comment]
Can do! I'll sneak that into the next update.

Edit: Gonna postpone this until 1.13/1.14

**Comment by wizard1399** [comment]
I have another request since this one is postponed. Could you add a ritual that teleports to the wither arena but with a different or no entity summoned? 
mods.ArcaneWorld.createRitualArena(stringName, displayName, entitySummoned, [IIngredients]

Entity summoned could be null and a return portal would be placed by default. The idea being that the arena could be used as a trial space for Deep Mob Learning or for setting up boss battles for a pack.

**Comment by SeriousCreeper** [comment]
Would you be ok with accepting pull requests with this feature for the 1.12.2 version?

**Comment by Lemonszz** [comment]
Yup!

**Comment by SeriousCreeper** [comment]
Super late, but just opened a pull request for it. Let me know if it looks good!
