### ISSUE TITLE
Crash due to Wither Skull Griefing Event

### ISSUE THREAD

**Issue by DarkYuan** [Lemonszz/ArcaneWorld#6]
---
**Mod Version**:  arcaneworld-1.12.2-0.0.8

**Forge Version**: forge-14.23.5.2776

**This issue occurs on the lastest version of Forge? (Y/N)**: Untested, will reply with results

**Crash Log (Post to Pastebin/Other Text hosting)**: [[Pastebin Link]](https://pastebin.com/x5CSmWBF)

**What happens**: Upon approaching a Wither in the overworld, if it shoots a skull the game crashes

**Comment by DarkYuan** [comment]
Tested again on latest version, forge-14.23.5.2796
Arcane World and Various Oddities installed [[Pastebin Link]](https://pastebin.com/jWcReRP0)

I thought it might have had something to do with that other mod, since their Giant mob can actually break through the ceiling blocks in the dungeon.

**Comment by TimGoll** [comment]
Same thing still hapens on forge *.68
But it happened while walking through the nether

**Comment by Lemonszz** [comment]
Fixed (Finally) pending next release.
