### ISSUE TITLE
Bug with the Recaller... or the Wither Arena Ritual, maybe both

### ISSUE THREAD

**Issue by Asveste** [Lemonszz/ArcaneWorld#7]
Please fill out this template when submitting an issue.

---
**Mod Version**:0.0.8

**Forge Version**:14.23.5.2808

**This issue occurs on the lastest version of Forge? (Y/N)**:Y

**Crash Log (Post to Pastebin/Other Text hosting)**: https://pastebin.com/kPG7meS6

**What happens**: Use the Recaller in the Overworld. Then do the "Wither Arena Ritual". Defeat the Wither. Instead of using the portal to go back, now use the Recaller to go back. I was told that this is a bug and I should report it.

**Comment by Lemonszz** [comment]
This is fixed pending the next release
